<?php
/* $Id$ */

/**
 * @file
 * Shows who has visited a user's profile lately.
 * 
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 */

/**
 * Implementation of hook_user();
 */
function user_visits_user($op, &$edit, &$account, $category = NULL) {
  global $user;

  if ($op == 'view') {
    //Count view
    if ($user->uid != $account->uid) {
      user_visits_count($account->uid, $user->uid);
    }
    
    $i = 1;
    $visitors = user_visits_latest($account->uid);
    if (is_array($visitors)) {
      foreach ($visitors as $visitor) {
        $account = user_load(array('uid' => $visitor->vuid));
        $output = theme('user_visit', $account, $visitor->visit);
        
        $items[] = array(
          'value' => $output ? $output : t('No visits by now'),
          'class' => $i,
        );
        $i++;
      }
    }
    
    return array(t('Profile visits') => $items);
  }
}

/**
 * Remember a user's visit
 * @param uid the visitors user id
 * @param vuid the visited user's user id
 */
function user_visits_count($uid, $vuid) {
  db_query("DELETE FROM {user_visits} WHERE uid=%d AND vuid=%d", $uid, $vuid);
  db_query("INSERT INTO {user_visits} (uid, vuid, visit) VALUES (%d, %d, %d)", $uid, $vuid, time());
}

/**
 * Get the latest visitors
 * @param uid an integer representing a user id
 * @param limit an integer
 */
function user_visits_latest($uid, $limit = 10) {
  $result = db_query("SELECT * FROM {user_visits} WHERE uid=%d ORDER BY visit DESC LIMIT %d", $uid, $limit);
  while ($visitor = db_fetch_object($result)) {
    $visitors[] = $visitor;
  }
    
  return $visitors;
}

/**
 * Theme a user object
 * @param user a user object
 * @return a themed user object in html
 */
function theme_user_visit($user, $timestamp = NULL) {
  $output  = "<div class=\"profile\">\n";
  $output .= theme('user_picture', $user);
  $output .= ' <div class="name">'. theme('username', $user) ."</div>\n";
  if ($timestamp) {
    $output .= " <div class=\"visit\">". t('!time ago', array('!time' => format_interval(time() - $timestamp))) ."</div>\n";
  }
  $output .= "</div>\n";

  return $output;
}

